### ISSUE TITLE
Is there a way of inserting default values into a payload?

### ISSUE THREAD

**Issue by jasonquigleyhpecom** [pb33f/libopenapi#152]
Hi Dave,

`kin-openapi` has a neat little trick:

```
	// Indicates whether default values are set in the
	// request. If true, then they are not set
	SkipSettingDefaults bool
```

Is there any way of achieving the same with `libopenapi`?

Thanks!

**Comment by daveshanley** [comment]
Can you tell me how you would expect to use this feature in the library, design me an API and tell me how you want it to feel when using it? I'm asking like this because I can make anything happen with the magic of code. 

So I want to get the experience right. When you say 'payload,' that means so many different things to me - so can you help me understand explicitly what you'd like to experience here? Defaults mean various things in the library based on context.

**Comment by jasonquigleyhpecom** [comment]
Hi Dave,

with `kin-openapi` you can choose to have it inject the default values of the schema properties into the request body JSON. I know this isn't and probably shouldn't be in your validator. 

I was really wondering if there is a way to traverse the model and pick out properties that have default values to be able to perform a merge with a JSON payload in the request body. That could perhaps be a helper function in `libopenapi`.

Thanks for your great work!

**Comment by daveshanley** [comment]
Hi Jason, 

I see what you mean, there isn't really any way to do what you're asking today, except for manually building the code to do it :). There IS, however going to be support for generating examples based on any schema in an OpenAPI Doc. I actually need this feature for other pb33f tools.

It's partially documented in #107, however it sounds like your request could be a part of that feature?

**Comment by jasonquigleyhpecom** [comment]
Hi Dave,

I think you're right, it could be part of that feature. Possibly producing a `json` example and then using [json-patch](github.com/evanphx/json-patch) to merge in a supplied `json` payload.

I'll close this issue as I think #107 will address it.

Thank you!
