### ISSUE TITLE
Can't export specs in yaml after resolving external (relative paths) references

### ISSUE THREAD

**Issue by oliviernguyenquoc** [pb33f/libopenapi#167]
I want to load a OpenAPI 3.1 specs, resolve external references (ExternalValue keys: relative paths) and generate the yaml with no more external references.

libopenapi seems to be the perfect tool for that.

Resolver seems to work (can't see how to be sure) but in tests like [here](https://github.com/pb33f/libopenapi/blob/86f5f3e7cdf0152c417380dedfff15efbf9b956b/resolver/resolver_test.go#L87C2-L87C47), you access to a private filed "resolvedRoot" that can't be accessed normally.

In the doc, it said "The document is now much, much bigger than it was before and there is duplication everywhere, but the document now exists in a state, as if $ref and JSON Pointers did not exist.

We **don’t recommend saving** or rendering a resolved spec, it’s probably going to be gigantic"

In my case, I need to save it. How can I do it, as resolvedRoot is a private field ?

**Comment by daveshanley** [comment]
You are the first person with this usecase. Congrats! I was wondering if anyone would ever reach out about this.

So the good news is that you have everything you need. The resolver is an engine, it does not really hold state, the `resolvedRoot` is actually coming from the index (*index.SpecIndex) (https://github.com/pb33f/libopenapi/blob/main/resolver/resolver.go#L54)

The resolver is destructive, because it stitches together all the references using the index, the root node will
become a potentially very large data structure in memory, depends on your spec.

To get access to this root node?

`index.GetRootNode()` (https://github.com/pb33f/libopenapi/blob/main/index/spec_index.go#L135)

Extract it from the index, not the resolver, the resolver is using the index and mutating it, as it's all pointer based.

**Comment by oliviernguyenquoc** [comment]
Thank you ! 

I wasn't able to find this method by myself.
