### ISSUE TITLE
Recent fix to indexing enums causes not all enums to be indexed

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#175]
The change here https://github.com/pb33f/libopenapi/pull/169 caused some of our tests to start failing as all the enums we were expecting to be in the index are no longer in the index.

For example in this spec:

```
openapi: 3.1.0
servers:
  - url: http://localhost:8080
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  enumRef:
                    $ref: '#/components/schemas/enum'
                  enum:
                    type: string
                    enum: [big, small]
                    nullable: true
components:
  schemas:
    enum:
      type: [string, null]
      enum: [big, small]
```

The enum in the component named `enum` is not contained within the index anymore

**Comment by TristanSpeakEasy** [comment]
reverting to `v0.10.3` fixes the issue

**Comment by daveshanley** [comment]
I think this may be a case of 'unfix the bug, we need the bug'. Technically the new behavior is correct, because the property named `enum` is not an enum, so it should not be indexed.

However the bug that exists in `v0.10.3` is something you've come to depend on. 

So, I think the solution here, is the same as the circular references approach. The option to include properties named `enum` into the index, or ignore them (default is to ignore, which is correct in my opinion)

But you can flip a bit in the Index Config or via a method to ignore that check and revert back to the pre bugfix behavior. 

Thoughts?

**Comment by daveshanley** [comment]
OK, I will loop back around on this, more intelligence on deciding what is and is not an enum is needed.

**Comment by TristanSpeakEasy** [comment]
fixed
