### ISSUE TITLE
What's the right way to specify a `null` enum variant?

### ISSUE THREAD

**Issue by srir** [pb33f/libopenapi#179]
I've been digging through the OpenAPI and json-schema specs trying to figure this out, and haven't had much luck.

For an enum that's one of a couple of static strings, or `null`, what's the right way?

Currently I've got:

```
{
    "type": "string",
    "enum": ["foo", "bar", "'null'"]
}
```

(note the `'null'` - I read somewhere that I now can't find that this is the way to specify a null value, vs a bare `null`). it seems to be "valid" according to libopenapi, but I'm wondering if it's just treating that as a string vs. an actual `null` value.

**Comment by TristanSpeakEasy** [comment]
@srir this should be 

```
{
    "type": "string",
    "enum": ["foo", "bar", "null"]
}
```

otherwise you are double quoting it. But you are correct it can't be `"enum": ["foo", "bar", null]` that is not valid OpenAPI.

Whether it then marks that type as "nullable" or is treated as nullable is up to the tooling you use (or have implemented) to determine as libopenapi won't set the `Nullable` field on a schema to true when this happens.

For example in our tooling we detect there is a `"null"` string in the list and then treat that as Nullable overriding the value of `schema.Nullable`

**Comment by daveshanley** [comment]
@TristanSpeakEasy has the right answer @srir .
