### ISSUE TITLE
Feature Request: Ability to resolve all schemas early

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#27]
It would be great to have a way after loading the document to have each schema prebuilt instead of needing to call "Schema.Schema()" while iterating through the document and needing to deal with the build errors.

Basically I would want to be able to load & validate the document immediately and then have the confidence to iterate through the document knowing it is a valid document and I don't need to deal with any errors caused by a invalid document later

**Comment by daveshanley** [comment]
This is a tricky one because it could end up exploding your app. 

Unless you're 100% sure you have no circular references, resolving everything at once will send your application into a never-ending black hole. This was the original design that I struggled with for months to make right.

The big issue is polymorphism, `allOf`, `oneOf` and `anyOf` abuse creates endless circular paths that are very deep and just about impossible to track. 

I am open to the feature, but it must come with a big warning label. I've watched my machines metaphorically start to smoke when loading in gigantic schemas with lots and lots of circles.

**Comment by TristanSpeakEasy** [comment]
Okay that makes sense, I am coming from kin-openapi where I can just iterate through everything but yeah it explodes on big schemas like stripes.

What is the intended usage then? And how do you avoid at the time you are going to build a schema hitting a circular reference? Does the check on load avoid that happening?

Also why doesn't the Schema() method return the error at build time? Needing to check the separate GetBuildError method is awkward and not a standard go pattern.

**Comment by daveshanley** [comment]
One of the reasons I created this library was to handle monster, enterprise-grade, messy, dirty auto-generated nightmare OpenAPI specs; circular references are by far the most offensive when designing for speed.

The intended use is that schemas don't exist until you need them. When you need them, you resolve them; they resolve one level at a time (which is why `SchemaProxy` exists). This is to prevent run-away looping and exploding processors.

The load check now reports circular errors (via your request in #18). This way, you know where NOT to resolve because your code will be set on a never-ending journey if you do.

The reason why I avoided the error return on `Schema()` was so it was easier to use, assuming that the spec is valid and doesn't
contain bad schemas, that way code is a lot more fluid:

```
thing.Schema().somethingElse
```

Feels a lot easier and less boilerplatey than

```
schema, err := thing.Schema()
if err != nil {
 // do something
}

// continue
```

over and over.

It's pretty easy to add another version of `Schema()`; however that will return any build error and the schema if that helps solve your issue.

**Comment by TristanSpeakEasy** [comment]
Yeah that makes perfect sense 👍 are the errors returned via the circular references check easy enough to associate with a instance of a schema now they have been unwrapped as per https://github.com/pb33f/libopenapi/issues/18?

As we could be dealing with any spec under the sun it is likely we will always need to check for an error so an API that returns it at build time would be appreciated.

Though I will dig deeper into the circular references implementation as we have our own tracking of this in our code and it might be nice to get rid of that and figure out how to know when something might end up going into circular reference hell

**Comment by daveshanley** [comment]
The original `[]*resolver.ResolvingError` has more detail in it that the unpacked error, 

```
type ResolvingError struct {
	Error error
	Node  *yaml.Node
	Path  string
}
```
is re-rendered into `[]error` using this: 

```
 fmt.Errorf("%s: %s [%d:%d]", resolvingErrors[r].Error.Error(),
                    resolvingErrors[r].Path, resolvingErrors[r].Node.Line, resolvingErrors[r].Node.Column))
```
so, all the details are there, but the error message will need parsing to pull all the details out.

It might be worth adding a new method with a third return argument that breaks `[]error` (for building errors) and `[]*resolver.ResolvingError` (resolving/lookups/circular-refs) to make this data available natively, instead of re-extracting it from a stringified error.

**Comment by TristanSpeakEasy** [comment]
Well if the `resolver.ResolvingError` type has an Error method added that builds the error string like you have shown, it would then fulfil the `error` interface and you could return it in the list of errors without needing to do any additional "handling" of them

**Comment by daveshanley** [comment]
Regarding the error return with a `Build()` variation, that's pretty simple. I can add that in the next patch. Would it be possible to add it as a separate issue, so we don't mix these two threads?

**Comment by daveshanley** [comment]
In `v0.3.2` The errors returned contain rich details about all circular errors now.

Example available at: 
https://github.com/pb33f/libopenapi#extracting-circular-refs-and-resolving-errors-when-building-a-document

**Comment by daveshanley** [comment]
I'm going to close this issue as 'not planned' because I don't plan on building the 'auto resolve all schemas' feature, it would break the design of the library in significant ways.
