### ISSUE TITLE
Deleting path item

### ISSUE THREAD

**Issue by panperla** [pb33f/libopenapi#77]
Hi and thanks for the great library. We were using your lib in various read/analyse scenarios and it is doing great job. We are mostly using it during execution of build pipelines. We have a need to remove some PathItems and serialize altered document for the need of javascript sdk generation based on altered version of document. 
Unfortunately I have stuck on deleting the whole PathItem from document. As far as Mutating specific fields works great but deleteing PathItem is not affecting final serialized document. 
I'm suspecting it has something to do with GoLow() misusage but I would appreciate some feedback on that.
Let's say we want to delete all Paths:
```
type OpenApiCleaner struct {
	Document libopenapi.Document
	ModelV3  *libopenapi.DocumentModel[v3.Document]
}

func (o *OpenApiCleaner) RemoveItemsWithSecurityName(item string) {
	for path, _ := range o.ModelV3.Model.Paths.GoLow().PathItems {
		delete(o.ModelV3.Model.GoLow().Paths.Value.PathItems, path)
	}
	d, err := o.Document.Serialize()
	if err != nil {
		fmt.Print(err)
	}
	fmt.Print(string(d))
}
```

**Comment by daveshanley** [comment]
Hi! Thanks for your feedback and comments.

The problem you see here is that only minimal mutation capability is available to the model. If you're changing the value of something, it works well - if you're modifying the structure of the model, however (like this example), it runs out of power at the moment.

Nothing is removed when you delete paths and then serialize because you're deleting pointers rather than actual nodes. 

There is a root node attached to the document. This root node is the original OpenAPI spec that sits underneath the model. The model is extracted (i.e., all the nodes pointing to values) are referenced from this higher level abstraction. 

So to delete the values, you will need to delete them from the underlying OpenAPI node tree. Editing values works fine because editing a pointer works excellently; however, deleting a reference to the node from the model won't remove the node. The node is still in place in the underlying node tree.

The `Serialize()` method renders the underlying node tree, NOT the model abstracted from it, which is why nothing is being removed. 

`libopenapi` is optimized for reading models vs. writing them - however, as more use cases arise, writing should be given some love and attention.

**Comment by panperla** [comment]
Dave thank you for prompt feedback and clarification. I will investigate the modification on the root document than.
