### ISSUE TITLE
Feature: Upgrade indexer to use native `io/fs` interfaces.

### ISSUE THREAD

**Issue by daveshanley** [pb33f/libopenapi#85]
As discussed in #83, This feature would introduce [https://pkg.go.dev/io/fs](https://pkg.go.dev/io/fs) as an interface to allow references to be stored in abstracted storage like databases.

**Comment by dedefer** [comment]
really looking forward to this feature

now i use [kin-openapi](https://github.com/getkin/kin-openapi/)
because this is only library that [allows you to override fs](
https://github.com/getkin/kin-openapi/blob/master/openapi3/loader.go#L36), and i need to parse openapi specs from inmemory fs

But it has poor error messages, so i want to replace it with libopenapi

**Comment by daveshanley** [comment]
I am actively working on this feature.

**Comment by daveshanley** [comment]
This feature is now available in `v0.9.3`

The index configuration now has a new property of `FSHandler`, which accepts anything that implements the `fs.FS` interface. 

[Documentation is available here](https://pb33f.io/libopenapi/index/#using-a-custom-fsfs-resolver)
